#arrays


In [4]:
from array import*
a=array("i",[1,2,3])#intialising elements
for i in a:
    print(i,end=" ")
    

1 2 3 

In [3]:
 #adding elements(append,insert,extend
from array import*
a=array("i",[1,2,3])
a.append(4)
a.extend([4,5])
a.insert(2,3)
print(a)
a.remove(5)#remove ,pop
print(a)
a.pop(2)
print(a)
a.reverse()
print(a)

array('i', [1, 2, 3, 3, 4, 4, 5])
array('i', [1, 2, 3, 3, 4, 4])
array('i', [1, 2, 3, 4, 4])
array('i', [4, 4, 3, 2, 1])


print(a.count(4))#conting of numbers and index of specific number
print(a.index(2))
a.reverse() #mam plz check this output
print(a)

In [5]:
from array import*
a=array("i",[4,4,3,2,1])

print(a.count(4))#index and count
print(a.index(4))
a.reverse()#reverse
print(a)
print(len(a))#len
b=a
print(b)
print(id(a))#adress
print(type(a))


2
0
array('i', [1, 2, 3, 4, 4])
5
array('i', [1, 2, 3, 4, 4])
80938032
<class 'array.array'>


#numpy(numerical python)


In [44]:
from numpy import *
a=array([
    [1,2,3],
    [4,5,6]
])
print(a.ndim)#no.of.dimensions
print(a.size)#size of array
print(a.shape)#shape
print(a.itemsize)#each element size
print(a.dtype)
print(type(a))

2
6
(2, 3)
4
int32
<class 'numpy.ndarray'>


In [64]:
#ways to ceate numpy
from numpy import*
a=arange(1,10).reshape(3,3)
print(a)
a=array([1,2,3],"f")
print(a)
a=zeros(5,"i")
print(a)
a=ones(5,"i")
print(a)
b=logspace(1,10,20)
print(b)
c=linspace(1,10,20)
print(c)
d=eye(4,4,k=1,dtype="i")
print(d)
d=random.rand(2,3)#random values,but values between 0 and 1 with 2*3 
print(d)
e=random.ranf(3)
print(e)
e=random.randint(0,4,size=(3,3))
print(e)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1. 2. 3.]
[0 0 0 0 0]
[1 1 1 1 1]
[1.00000000e+01 2.97635144e+01 8.85866790e+01 2.63665090e+02
 7.84759970e+02 2.33572147e+03 6.95192796e+03 2.06913808e+04
 6.15848211e+04 1.83298071e+05 5.45559478e+05 1.62377674e+06
 4.83293024e+06 1.43844989e+07 4.28133240e+07 1.27427499e+08
 3.79269019e+08 1.12883789e+09 3.35981829e+09 1.00000000e+10]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
[[0.48878666 0.07580328 0.70422882]
 [0.17343196 0.20761799 0.02714359]]
[0.12218715 0.80498498 0.25215547]


In [108]:
a=array([1,2,[3,4,[5,6]],6,6])
print(len(a))
a=array([11,2,3])
print(a[1])

a=array([[1,2,3],[4,5,6]])
print(a[1][1])

a=array([[1,2,3],[4,5,6],[7,8,9]])
print(a[1:,1:])

a=array([11,2,3,5,6])
print(a[[1,3,0]])#advanced indexing
a=array([2,3,[1,[2,3,5]],6])#nested list
print(a[2][1][0])
a=array([[1,2,3],[4,5,6],[7,8,9]])#advanced indexing of n dimensions

print(a[[1,1],[0,2]])
print(a[a>3])#boolean indexing
b=transpose(a,axes=(1,0))#transpose
print(b)
a=arange(0,30).reshape(2,5,3)#reshape and transpose of nested list
print(a)
d=transpose(a,axes=(1,0,2))
print(d)
print(a[1,1,1])#fetching element from nested array


5
2
5
[[5 6]
 [8 9]]
[ 2  5 11]
2
[4 6]
[4 5 6 7 8 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[ 0  1  2]
  [15 16 17]]

 [[ 3  4  5]
  [18 19 20]]

 [[ 6  7  8]
  [21 22 23]]

 [[ 9 10 11]
  [24 25 26]]

 [[12 13 14]
  [27 28 29]]]
19


#scientific calculations

In [116]:
a=array([1,23,3,4])
b=array([1,4,5,6])
print(min(a))
print(max(a))
print(log(a))
print(std(a))
print(sort(a))


print(a+b)


1
23
[0.         3.13549422 1.09861229 1.38629436]
8.870597499605086
[ 1  3  4 23]
[[ 1 23  3  4]
 [ 1  4  5  6]]
[ 2 27  8 10]


In [120]:
#vstack and hstack
print(vstack(((a,b))))
print(hstack(((a,b))))
print(hstack([[a,b]]))

#axis
print(a.sum(axis=0))

[[ 1 23  3  4]
 [ 1  4  5  6]]
[ 1 23  3  4  1  4  5  6]
[[ 1 23  3  4]
 [ 1  4  5  6]]
31
